
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://pranayshah.xyz"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme
baseurl:

# Google tracking id

google-tracking-id: "UA-79013360-3"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Pranay Shah"
title: "Pranay Shah"
description: "Personal website of Pranay Shah. Opinions expressed are mine."
keywords: "pranay, shah"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: ""
# logo: "/img/author.png" # leave blank if you don't want a logo

# background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hello, World! 👋"

me-img: "/img/profile.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# # Icons for Web App mode (ignore icons below; custom icons placed in web-app.html)

# icon-36p: "/img/web-app/icon-36p.png"
# icon-48p: "/img/web-app/icon-48p.png"
# icon-72p: "/img/web-app/icon-72p.png"
# icon-96p: "/img/web-app/icon-96p.png"
# icon-144p: "/img/web-app/icon-144p.png"
# icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  # - image: "/img/timeline/spidertocat.png"
  #   date: "September 2013 - Today"
  #   description: "Saving the neighborhood!"
  - image: "/img/timeline/tesla.png"
    date: "March 2021"
    description: "Incoming Software Engineer at Tesla"
  - image: "/img/timeline/umich.jpg"
    date: "December 2020"
    description: "Graduated from the University of Michigan, Ann Arbor. Go Blue!"
  - image: "/img/timeline/tesla.png"
    date: "May 2020 - August 2020"
    description: "Software Engineering Intern at Tesla"
  - image: "/img/timeline/apple.jpg"
    date: "May 2019 - August 2019"
    description: "Software Engineering Intern at Apple"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "pranay@pranayshah.xyz"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb: ""
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  # - title: "facebook"
  #   url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/pranayshahxyz"
  - title: "linkedin"
    url: "https://linkedin.com/in/pranayshahxyz"
  - title: "github"
    url: "https://github.com/pranayshahxyz"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

# err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: pranayshah
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  # Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
